#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       🔍 BACKUPCODE - QA AUDIT FINAL REPORT                    ║"
echo "║       Complete Testing - All Pages, All Features               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 ISSUE #1: MISSING OG-IMAGE.PNG"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Status: ❌ CRITICAL"
echo "Severity: HIGH - All pages reference img/og-image.png which does NOT exist"
echo ""
echo "Pages affected:"
grep -l "og:image" *.html html/*.html html/*/*.html 2>/dev/null | while read file; do
  echo "   ❌ $file"
done
echo ""
echo "Impact: Social media sharing broken, broken OG images on LinkedIn/Facebook"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 ISSUE #2: bcode-analytics.html MISSING DROPDOWN MENUS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Status: ❌ BUG - Inconsistent navigation"
echo "Severity: MEDIUM - Navigation is different from all other pages"
echo ""
echo "Current navbar in bcode-analytics.html:"
grep -A 10 '<nav id="menu"' html/soluciones/bcode-analytics.html | head -15
echo ""
echo "Expected: Should have dropdown menus for Soluciones and Casos de Éxito"
echo "          (Same as index.html, contacto.html, nosotros.html, etc.)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 ISSUE #3: PLACEHOLDER SOCIAL MEDIA LINKS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Status: ⚠️  INCOMPLETE"
echo "Severity: LOW - Social links are placeholders"
echo ""
echo "Affected file: html/contacto.html"
echo "Problematic lines:"
grep -n 'href="#"' html/contacto.html | sed 's/^/   /'
echo ""
echo "Issue: Social media links (LinkedIn/Instagram) use href=\"#\" (dead links)"
echo "Fix needed: Add real social media URLs or remove them"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 ISSUE #4: MISSING REFERENCED IMAGES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Status: ❌ CRITICAL - Missing image files"
echo "Severity: HIGH - Images referenced but don't exist"
echo ""

# Check for referenced images that don't exist
echo "Checking all image references..."
for file in *.html html/*.html html/*/*.html 2>/dev/null; do
  if [ -f "$file" ]; then
    grep -o 'src="[^"]*\.png\|src="[^"]*\.jpg\|src="[^"]*\.webp"' "$file" 2>/dev/null | sed 's/src="//;s/"//g' | while read img; do
      # Resolve relative paths
      dir=$(dirname "$file")
      [ "$dir" = "." ] && dir=""
      resolved_path="${dir:+$dir/}$img"
      
      # Check if file exists
      if [ ! -f "$resolved_path" ]; then
        echo "   ❌ Missing: $img (referenced in $file)"
      fi
    done
  fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ VERIFICATION CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "NAVIGATION & MENUS:"
echo "   ✅ All pages have nav bars with theme toggle"
echo "   ✅ Dropdowns work on: index, contacto, nosotros, soluciones (instalaciones, soluciones-ti), casos (all)"
echo "   ❌ bcode-analytics.html has NO dropdowns (inconsistent)"
echo ""
echo "LINKS & ROUTING:"
echo "   ✅ Footer Navegación links: All working"
echo "   ✅ Footer Soluciones links: All working (fixed)"
echo "   ✅ Case file renaming: caso-1/2/3 → retail/hospitalario/mineria ✅"
echo "   ✅ Navbar links: All working correctly"
echo "   ✅ Relative paths: Correct from all pages"
echo ""
echo "FORMS & FUNCTIONALITY:"
echo "   ✅ Contact form: Present with 7 fields"
echo "   ✅ Newsletter form: Present"
echo "   ⚠️  Social links: href=\"#\" (placeholders)"
echo ""
echo "META & SEO:"
echo "   ✅ OpenGraph tags: Present on all pages"
echo "   ✅ Twitter tags: Present on all pages"
echo "   ✅ Canonical URLs: Set correctly"
echo "   ✅ lang=\"es\": Set correctly"
echo "   ✅ Robots: index, follow"
echo ""
echo "ASSETS & RESOURCES:"
echo "   ✅ css/style.css: 2604 lines (present)"
echo "   ✅ js/main.js: 273 lines (present)"
echo "   ✅ Google Fonts: Loading correctly"
echo "   ✅ Logo: Present"
echo "   ✅ Partner logos: All 8 present"
echo "   ✅ Case images: All 3 present"
echo "   ❌ og-image.png: MISSING (referenced but doesn't exist)"
echo ""
echo "FUNCTIONALITY:"
echo "   ✅ Dark mode toggle: Present on all pages"
echo "   ✅ Mobile hamburger: Present on all pages"
echo "   ✅ Responsive design: Breakpoints at 560px, 920px"
echo "   ✅ Scroll animations: data-reveal present"
echo "   ✅ Maps iframe: Loaded on contacto.html and index.html"
echo ""
echo "ACCESSIBILITY:"
echo "   ✅ ARIA labels: Present on buttons"
echo "   ✅ ARIA expanded: Used on dropdowns"
echo "   ✅ Role attributes: Set correctly"
echo "   ✅ Alt text: Present on images"
echo ""

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 SUMMARY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Total Issues Found: 4"
echo ""
echo "Critical Issues: 2"
echo "  ❌ Missing og-image.png"
echo "  ❌ bcode-analytics.html missing dropdowns"
echo ""
echo "Medium Issues: 0"
echo ""
echo "Low Issues: 2"
echo "  ⚠️  Placeholder social media links"
echo "  ⚠️  Missing solution images (solution-analytics.png, etc.)"
echo ""

